### ISSUE TITLE
 flag provided but not defined: -apiserver-override?

### ISSUE THREAD

**Issue by ananas-hebo** [kubernetes/node-problem-detector#147]
My k8s without rbac.
So  i use like : [docs usage](https://github.com/kubernetes/node-problem-detector#usage)

But i got a "flag provided but not defined: -apiserver-override" error.

yaml file:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-problem-detector
spec:
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      containers:
      - name: node-problem-detector
        command:
        - /node-problem-detector
        - --apiserver-override=http://centos-master2.ans:8080?inClusterConfig=false
        - --logtostderr
        - --kernel-monitor=/config/kernel-monitor.json
        image: registry-ans.chaoxing.com/google_containers/node-problem-detector:v0.2
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure node problem detector is in the same timezone
        # with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        #- name: config
        #  mountPath: /config
        #  readOnly: true
      volumes:
      - name: log
        # Config `log` to your system log directory
        hostPath:
          path: /var/log/
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: localtime
        hostPath:
          path: /etc/localtime
      #- name: config
      #  configMap:
      #    name: node-problem-detector-config
```
