### ISSUE TITLE
[Please] Fix README.md so that noobs can get to a working deployment quickly

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/node-problem-detector#209]
@max-rocket-internet has been diligent in pointing out some issue with Kubernetes deployment (#206). These issues remain unresolved and will trap (as they did me) noob users.

It's unclear whether my hacky fixes are correct but, to get everything working:

### 1. Registry
For the majority of users, 'staging-k8s.gcr.io` won't be appropriate, this could perhaps more conveniently be mapped to an environment variable `=${YOUR_REGISTRY}`
https://github.com/kubernetes/node-problem-detector/blob/f85b416b28639357c95a2c4a32b0f89b569ccb81/Makefile#L29

### 2. RBAC
I took @max-rocket-internet Helm sample and reused the `ServiceAccount` and `ClusterRoleBinding` in [`node-problem-detector.yaml`](https://github.com/kubernetes/node-problem-detector/blob/master/deployment/node-problem-detector.yaml):
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-problem-detector
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-problem-detector-binding
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-problem-detector
subjects:
- kind: ServiceAccount
  name: node-problem-detector
  namespace: kube-system
...
```
I then also changed the `DaemonSet` to run the containers under the Service Account using:
```
serviceAccountName: node-problem-detector
```

### 3. Command
The current command is incorrect:
```
/node-problem-detector --kernel-monitor=/config/kernel-monitor.json
```
Again, the Helm chart was helpful:
```
/node-problem-detector --logtostderr --system-log-monitors=...
```

### 4. Config
The documentation is clear but I found it confusing. `make` bundles the `config` directory into the image and so the Deployment's inclusion of a volume mount is redundant. Rather than be provided by default, this should perhaps be provided as "If you wish to override the images `/config` directory, you may use a `ConfigMap`..."

### 5. Kubernetes Engine
I'm using Kubernetes Engine and -- by default -- it uses [Container-Optimized OS (COS)](https://cloud.google.com/container-optimized-os). NPD incorrectly reports that COS is not supported. IIUC
* `kernel-monitor-filelog` doesn't (!) work with COS because COS provides no `/var/log/kern.log` so this configuration should be removed to avoid its errors.
* `docker-monitor-filelog` doesn't (!) work with COS because COS provides no `/var/log/docker.log` so this configuration should be removed too.
* There may be other configurations that need tweaking|removing.

Otherwise, NPD works under COS

#### 5. Apply not Create (Minor)
In my experience, it's generally better to `kubectl apply` than `kubectl create`.

Rather than:
```
kubectl create -f node-problem-detector.yaml
```
Use:
```
kubectl apply --filename=./node-problem-detector.yaml
```
I use long flags for clarity.
