### ISSUE TITLE
does inotify leaked?

### ISSUE THREAD

**Issue by chinglinwen** [kubernetes/node-problem-detector#297]
does the following outputs means inotify leaked?  as I follow this issue https://github.com/kubernetes/kubernetes/issues/7815

https://github.com/golang/exp/commit/292a51b8d262487dab23a588950e8052d63d9113#diff-913c4cd2428ce8671839b1afb2699b25

```shell
[root@online-node-81-116 ~]# for foo in /proc/*/fd/*; do readlink -f $foo; done |grep inotify |cut -d/ -f3 |xargs -I '{}' -- ps --no-headers -o '%p %U %c' -p '{}' |uniq -c |sort -nr
      5  6795 root     kubelet
      5     1 root     systemd
      2  6956 polkitd  polkitd
      2 16612 root     cadvisor
      1  7294 root     rsyslogd
      1  7058 root     crond
      1  6950 dbus     dbus-daemon
      1  3630 root     systemd-udevd
      1 17224 root     node-problem-de
[root@online-node-81-116 ~]#
```
```
[root@online-node-81-114 ~]# for foo in /proc/*/fd/*; do readlink -f $foo; done |grep inotify |cut -d/ -f3 |xargs -I '{}' -- ps --no-headers -o '%p %U %c' -p '{}' |uniq -c |sort -nr
      5     1 root     systemd
      5 18847 root     kubelet
      2   955 polkitd  polkitd
      2 10296 root     cadvisor
      1   982 root     crond
      1   959 dbus     dbus-daemon
      1   947 root     rsyslogd
      1   685 root     systemd-udevd
      1 48534 root     node-problem-de
[root@online-node-81-114 ~]# 
```

```
[root@online-node-81-116 ~]# ps -ef|grep node-prob
root     16251 13513  0 14:04 pts/0    00:00:00 grep --color=auto node-prob
root     17224 17164  0 Jun20 ?        00:03:07 /node-problem-detector --logtostderr --system-log-monitors=/config/kernel-monitor.json,/config/docker-monitor.json
[root@online-node-81-116 ~]# cd /proc/17224/fd
[root@online-node-81-116 fd]# ls |wc
     47      47     132
[root@online-node-81-116 fd]# find . | wc
     48      48     228
[root@online-node-81-116 fd]# ls -l
total 0
lrwx------ 1 root root 64 Jun 20 11:29 0 -> /dev/null
l-wx------ 1 root root 64 Jun 20 11:29 1 -> pipe:[46019]
lr-x------ 1 root root 64 Jun 24 10:30 10 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-00000000003bfd37-00058a252597e158.journal
lr-x------ 1 root root 64 Jun 24 10:30 11 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@c8265c6e83014519ab0f5a983fa9b1f0-0000000000449930-00058aacd7f75143.journal
lr-x------ 1 root root 64 Jun 24 10:30 12 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@c8265c6e83014519ab0f5a983fa9b1f0-0000000000404b30-00058a5bfb6a175b.journal
lr-x------ 1 root root 64 Jun 24 10:30 13 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-7374@dc8b3f2b0a38418f975bef216db5ee4e-000000000040ce73-00058a62fa0567b0.journal
lr-x------ 1 root root 64 Jun 24 10:30 14 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-00000000003661c9-000589ca9ecefba0.journal
lr-x------ 1 root root 64 Jun 24 10:30 15 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@c8265c6e83014519ab0f5a983fa9b1f0-000000000048c2b0-00058ada6e21fc0a.journal
lr-x------ 1 root root 64 Jun 24 10:30 16 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@ce0271d6e8924b1b9b74a8ecc3db0d45-000000000029a2d2-000589c8411d962a.journal
lr-x------ 1 root root 64 Jun 24 10:30 17 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-000000000048d102-00058adb0a078ebe.journal
lr-x------ 1 root root 64 Jun 24 10:30 18 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@c8265c6e83014519ab0f5a983fa9b1f0-0000000000000001-000589d9080d7bff.journal
lr-x------ 1 root root 64 Jun 24 10:30 19 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@ce0271d6e8924b1b9b74a8ecc3db0d45-000000000032204c-000589c9601582e1.journal
l-wx------ 1 root root 64 Jun 20 11:29 2 -> pipe:[46020]
lr-x------ 1 root root 64 Jun 24 10:30 20 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@c8265c6e83014519ab0f5a983fa9b1f0-000000000039df1c-00058a06586f2948.journal
lr-x------ 1 root root 64 Jun 24 10:30 21 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@c8265c6e83014519ab0f5a983fa9b1f0-000000000046aca1-00058ac41f353aff.journal
lr-x------ 1 root root 64 Jun 24 10:30 22 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-00000000002ef2d6-000589c8f1bc84cd.journal
lr-x------ 1 root root 64 Jun 24 10:30 23 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@ce0271d6e8924b1b9b74a8ecc3db0d45-0000000000300303-000589c9179a7248.journal
lr-x------ 1 root root 64 Jun 24 10:30 24 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@000589d8eb2095a6-27dc0ca8b82440ea.journal~
lr-x------ 1 root root 64 Jun 24 10:30 25 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000.journal
lr-x------ 1 root root 64 Jun 24 10:30 26 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-0000000000449b64-00058aacf0126697.journal
lr-x------ 1 root root 64 Jun 24 10:30 27 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-0000000000240c47-000589c74494332c.journal
lr-x------ 1 root root 64 Jun 24 10:30 28 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@c8265c6e83014519ab0f5a983fa9b1f0-00000000004287b0-00058a95732009c7.journal
lr-x------ 1 root root 64 Jun 24 10:30 29 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@ce0271d6e8924b1b9b74a8ecc3db0d45-00000000002784ff-000589c7fbc5d1cd.journal
lr-x------ 1 root root 64 Jun 24 10:30 3 -> /dev/kmsg
lr-x------ 1 root root 64 Jun 24 10:30 30 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@ce0271d6e8924b1b9b74a8ecc3db0d45-0000000000343c57-000589c9a7814cbf.journal
lr-x------ 1 root root 64 Jun 24 10:30 31 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@ce0271d6e8924b1b9b74a8ecc3db0d45-00000000002335b2-000589c72ab40984.journal
lr-x------ 1 root root 64 Jun 24 10:30 32 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-000000000042881f-00058a9577aa18ed.journal
lr-x------ 1 root root 64 Jun 24 10:30 33 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-7374.journal
lr-x------ 1 root root 64 Jun 24 10:30 34 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@000589d908546b83-d0eee907b6989497.journal~
lr-x------ 1 root root 64 Jun 24 10:30 35 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@c8265c6e83014519ab0f5a983fa9b1f0-00000000003bf1a9-00058a247c040089.journal
lr-x------ 1 root root 64 Jun 24 10:30 36 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-000000000020f793-000589c1666bff79.journal
lr-x------ 1 root root 64 Jun 24 10:30 37 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system.journal
lr-x------ 1 root root 64 Jun 24 10:30 38 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-00000000004053b4-00058a5c7827a4ac.journal
lr-x------ 1 root root 64 Jun 24 10:30 39 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-0000000000352bc3-000589c9c836b101.journal
lrwx------ 1 root root 64 Jun 24 10:30 4 -> anon_inode:[eventpoll]
lr-x------ 1 root root 64 Jun 24 10:30 40 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@c8265c6e83014519ab0f5a983fa9b1f0-00000000003e38b4-00058a3d8e1e8cd6.journal
lr-x------ 1 root root 64 Jun 24 10:30 41 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-0000000000287b7d-000589c81b1176fa.journal
lr-x------ 1 root root 64 Jun 24 10:30 42 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@ce0271d6e8924b1b9b74a8ecc3db0d45-00000000002ddd22-000589c8cb37076d.journal
lr-x------ 1 root root 64 Jun 24 10:30 43 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@ce0271d6e8924b1b9b74a8ecc3db0d45-000000000025668c-000589c7b0285662.journal
lr-x------ 1 root root 64 Jun 24 10:30 44 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-00000000003e45a2-00058a3e4b23cab0.journal
lr-x------ 1 root root 64 Jun 24 10:30 45 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/system@ce0271d6e8924b1b9b74a8ecc3db0d45-00000000002bbf18-000589c8856a1d56.journal
lr-x------ 1 root root 64 Jun 24 10:30 46 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-000000000039ea09-00058a06f89d8091.journal
lr-x------ 1 root root 64 Jun 24 10:30 47 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-1000@17e934ca6d5f4bc79cf7bcb33a69bccb-000000000046b345-00058ac4684d417a.journal
lr-x------ 1 root root 64 Jun 24 10:30 5 -> anon_inode:inotify
lrwx------ 1 root root 64 Jun 24 10:30 6 -> socket:[84034]
lrwx------ 1 root root 64 Jun 24 10:30 7 -> socket:[86072]
lr-x------ 1 root root 64 Jun 24 10:30 9 -> /var/log/journal/b7fc4c26a8dc4619bc76c4b952ba7adf/user-7374@dc8b3f2b0a38418f975bef216db5ee4e-000000000000e161-000589d908d3c472.journal
[root@online-node-81-116 fd]# 
```

```yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-problem-detector
  namespace: yunwei
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-problem-detector
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups:
    - ''
    resources:
    - '*'
    verbs:
    - update
    - patch
    - get
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding
metadata:
  name: node-problem-detector
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-problem-detector
  # name: admin
subjects:
- kind: ServiceAccount
  name: node-problem-detector
  namespace: yunwei

---
apiVersion: v1
data:
  kernel-monitor.json: |
    {
        "plugin": "kmsg",
        "logPath": "/dev/kmsg",
        "lookback": "5m",
        "bufferSize": 10,
        "source": "kernel-monitor",
        "conditions": [
            {
                "type": "KernelDeadlock",
                "reason": "KernelHasNoDeadlock",
                "message": "kernel has no deadlock"
            },
            {
                "type": "ReadonlyFilesystem",
                "reason": "FilesystemIsReadOnly",
                "message": "Filesystem is read-only"
            }
        ],
        "rules": [
            {
                "type": "temporary",
                "reason": "OOMKilling",
                "pattern": "Kill process \\d+ (.+) score \\d+ or sacrifice child\\nKilled process \\d+ (.+) total-vm:\\d+kB, anon-rss:\\d+kB, file-rss:\\d+kB.*"
            },
            {
                "type": "temporary",
                "reason": "TaskHung",
                "pattern": "task \\S+:\\w+ blocked for more than \\w+ seconds\\."
            },
            {
                "type": "temporary",
                "reason": "UnregisterNetDevice",
                "pattern": "unregister_netdevice: waiting for \\w+ to become free. Usage count = \\d+"
            },
            {
                "type": "temporary",
                "reason": "KernelOops",
                "pattern": "BUG: unable to handle kernel NULL pointer dereference at .*"
            },
            {
                "type": "temporary",
                "reason": "KernelOops",
                "pattern": "divide error: 0000 \\[#\\d+\\] SMP"
            },
            {
                "type": "permanent",
                "condition": "KernelDeadlock",
                "reason": "AUFSUmountHung",
                "pattern": "task umount\\.aufs:\\w+ blocked for more than \\w+ seconds\\."
            },
            {
                "type": "permanent",
                "condition": "KernelDeadlock",
                "reason": "DockerHung",
                "pattern": "task docker:\\w+ blocked for more than \\w+ seconds\\."
            },
            {
                "type": "permanent",
                "condition": "ReadonlyFilesystem",
                "reason": "FilesystemIsReadOnly",
                "pattern": "Remounting filesystem read-only"
            }
        ]
    }
  docker-monitor.json: |
    {
        "plugin": "journald",
        "pluginConfig": {
            "source": "dockerd"
        },
        "logPath": "/var/log/journal",
        "lookback": "5m",
        "bufferSize": 10,
        "source": "docker-monitor",
        "conditions": [],
        "rules": [
            {
                "type": "temporary",
                "reason": "CorruptDockerImage",
                "pattern": "Error trying v2 registry: failed to register layer: rename /var/lib/docker/image/(.+) /var/lib/docker/image/(.+): directory not empty.*"
            }
        ]
    }
kind: ConfigMap
metadata:
  name: node-problem-detector-config
  namespace: yunwei
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-problem-detector
  namespace: yunwei
  labels:
    app: node-problem-detector
spec:
  selector:
    matchLabels:
      app: node-problem-detector
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      serviceAccountName: node-problem-detector
      # nodeSelector:
      #   nodedetect: 'true'
      tolerations:
      - operator: "Exists"
      containers:
      - name: node-problem-detector
        command:
        - /node-problem-detector
        - --logtostderr
        - --system-log-monitors=/config/kernel-monitor.json,/config/docker-monitor.json
        image: googlecontainer/node-problem-detector:v0.6.3
        resources:
          limits:
            cpu: 10m
            memory: 80Mi
          requests:
            cpu: 10m
            memory: 80Mi
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure node problem detector is in the same timezone
        # with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: log
        # Config `log` to your system log directory
        hostPath:
          path: /var/log/
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config
        configMap:
          name: node-problem-detector-config
          items:
          - key: kernel-monitor.json
            path: kernel-monitor.json
          - key: docker-monitor.json
            path: docker-monitor.json

```

node-problem-detector:v0.6.3

```
[root@online-node-81-116 ~]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@online-node-81-116 ~]# uname -a
Linux online-node-81-116 4.14.15-1.el7.elrepo.x86_64 #1 SMP Tue Jan 23 20:28:26 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@online-node-81-116 ~]# 

[root@online-node-81-116 ~]# docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
