### ISSUE TITLE
Failing to start NPD due to plugin path file doesn't exists

### ISSUE THREAD

**Issue by harighub** [kubernetes/node-problem-detector#355]
I've followed the instructions described at [link]( https://kubernetes.io/docs/tasks/debug-application-cluster/monitor-node-health/ ) using latest image version k8s.gcr.io/node-problem-detector:v0.7.1 on Mac HighSierra 10.13.6

```
F0922 00:32:38.970308       1 custom_plugin_monitor.go:78] Failed to validate custom plugin config {Plugin:custom PluginGlobalConfig:{InvokeIntervalString:0xc00038cb10 TimeoutString:0xc00038cb20 InvokeInterval:30s Timeout:5s MaxOutputLength:0xc0002a2168 Concurrency:0xc0002a2178 EnableMessageChangeBasedConditionUpdate:0x1e125a4} Source:network-custom-plugin-monitor DefaultConditions:[] Rules:[0xc000299810] EnableMetricsReporting:0xc0002a2190}: rule path "./config/plugin/network_problem.sh" does not exist. Rule: &{Type:temporary Condition: Reason:ConntrackFull Path:./config/plugin/network_problem.sh Args:[] TimeoutString:0xc00038cb30 Timeout:3s}
```
configMap was created using 

`kubectl create configmap node-problem-detector-config --from-file=config` looks like all config files seem to be created in the CM and properly mounted to NPD container but all dependent plugin files under that directory were missing, I think which is expected behavior.

node-problem-detector.yaml
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-problem-detector
  namespace: kube-system
  labels:
    app: node-problem-detector
spec:
  selector:
    matchLabels:
      app: node-problem-detector
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      containers:
      - name: node-problem-detector
        command:
        - /node-problem-detector
        - --logtostderr
        - --system-log-monitors=/config/kernel-monitor.json,/config/docker-monitor.json
        - --config.custom-plugin-monitor=/config/network-problem-monitor.json,/config/custom-plugin-monitor.json
        image: k8s.gcr.io/node-problem-detector:v0.7.1
        resources:
          limits:
            cpu: 10m
            memory: 80Mi
          requests:
            cpu: 10m
            memory: 80Mi
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure node problem detector is in the same timezone
        # with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: log
        # Config `log` to your system log directory
        hostPath:
          path: /var/log/
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config
        configMap:
          name: node-problem-detector-config
          items:
          - key: kernel-monitor.json
            path: kernel-monitor.json
          - key: docker-monitor.json
            path: docker-monitor.json
          - key: network-problem-monitor.json
            path: network-problem-monitor.json
          - key: custom-plugin-monitor.json
            path: custom-plugin-monitor.json
```

what is recommended approach to mount custom plugin files to NPD container? I had issues building image locally on my Mac due to Debian system package files missing.
