### ISSUE TITLE
Unable to get the kubelet monitor to run

### ISSUE THREAD

**Issue by dylanlingelbach** [kubernetes/node-problem-detector#584]
I am running into a similar issue as https://github.com/kubernetes/node-problem-detector/issues/214 and https://github.com/kubernetes/node-problem-detector/issues/439

I am using the `k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.8` image (which doesn't have `systemd` installed) and installing it into a bottlerocket host that does have `systemd`.

Everything works great until I try to enable the kubelet monitor as that shells out to `systemctl` to get uptime of `kubelet`. 

I've tried mounting `/bin/systemctl` and the other suggestions in those issues without luck. 

Is mounting `systemctl` from the host the only way to get the kubelet monitor running? Or is installing `node-problem-detector` on the host itself a better solution?

**Comment by hjkatz** [comment]
I ran into these same problems and was able to successfully run node-problem-detector with access to `systemctl` and `docker` binaries using a wrapper Dockerfile image, like so:

```
FROM us.gcr.io/k8s-artifacts-prod/node-problem-detector/node-problem-detector:v0.8.9

RUN clean-install \
        curl \
        systemd \
        docker.io
```

I was also able to successfully get the `log-counter` and `health-checker` scripts and custom plugins to work (as expected with Node conditions and testing) with the following `daemonset.yaml`:

```yaml
    spec:
      # health-checker for kubelet uses the local network to check kubelet's /healthz
      hostNetwork: true
      containers:
      - name: node-problem-detector
        command:
        - /node-problem-detector
        - --logtostderr
        - --config.system-log-monitor=[files]
        - --config.custom-plugin-monitor=[files]
        image: custom-registry/custom-image:0.8.9
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure container is in the same timezone with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: config
          mountPath: /config
        - mountPath: /etc/machine-id
          name: machine-id
          readOnly: true
        - mountPath: /run/systemd/system
          name: systemd
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /var/run/dbus/
          name: dbus
          mountPropagation: Bidirectional
      volumes:
      - name: log
        # Config `log` to your system log directory
        hostPath:
          path: /var/log/
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config
        configMap:
          defaultMode: 0744
          name: node-problem-detector-config
      - name: machine-id
        hostPath:
          path: /etc/machine-id
          type: File
      - name: systemd
        hostPath:
          path: /run/systemd/system/
          type: Directory
      - name: dbus
        hostPath:
          path: /var/run/dbus/
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
```

I hope that this helps others that run into these challenges. Cheers!

Related Issue:
* #439
* #214 
* #592
