### ISSUE TITLE
Using the tool to test the results log view is incorrect

### ISSUE THREAD

**Issue by gssjl2008** [kubernetes/node-problem-detector#617]
#### Test command
```shell
echo "task docker:7 blocked for more than 300 seconds." |systemd-cat -t kernel
echo "task docker:7 blocked for more than 200 seconds." |systemd-cat -t kernel
```

####  configuration file

```yaml
[root@10-23-20-155 node-problem-detector]# cat node-problem-detector-config.yaml
apiVersion: v1
data:
  kernel-monitor.json: |
    {
        "plugin": "journald",
        "pluginConfig": {
           "source": "kernel"
         },
        "logPath": "/var/log/journal",
        "lookback": "10s",
        "bufferSize": 10,
        "source": "kernel-monitor",
        "conditions": [
          {
            "type": "KernelDeadlock",
            "reason": "KernelHasNoDeadlock",
            "message": "kernel has no deadlock"
          }
        ],
        "rules": [
           {
             "type": "temporary",
             "reason": "OOMKilling",
             "pattern": "Kill process \\d+ (.+) score \\d+ or sacrifice child\\nKilled process \\d+ (.+) total-vm:\\d+kB, anon-rss:\\d+kB, file-rss:\\d+kB.*"
           },
           {
             "type": "temporary",
             "reason": "TaskHung",
             "pattern": "task \\S+:\\w+ blocked for more than \\w+ seconds\\."
           },
           {
             "type": "temporary",
             "reason": "UnregisterNetDevice",
             "pattern": "unregister_netdevice: waiting for \\w+ to become free. Usage count = \\d+"
           },
           {
             "type": "temporary",
             "reason": "KernelOops",
             "pattern": "BUG: unable to handle kernel NULL pointer dereference at .*"
           },
           {
             "type": "temporary",
             "reason": "KernelOops",
             "pattern": "divide error: 0000 \\[#\\d+\\] SMP"
           },
           {
             "type": "permanent",
             "condition": "KernelDeadlock",
             "reason": "AUFSUmountHung",
             "pattern": "task umount\\.aufs:\\w+ blocked for more than \\w+ seconds\\."
           },
           {
             "type": "permanent",
             "condition": "KernelDeadlock",
             "reason": "DockerHung",
             "pattern": "task docker:\\w+ blocked for more than \\w+ seconds\\."
           }
         ]
       }

  docker-monitor.json: |
    {
        "plugin": "journald",
        "pluginConfig": {
            "source": "docker"
        },
        "logPath": "/var/log/journal",
        "lookback": "5m",
        "bufferSize": 10,
        "source": "docker-monitor",
        "conditions": [],
        "rules": [
            {
                "type": "temporary",
                "reason": "CorruptDockerImage",
                "pattern": "Error trying v2 registry: failed to register layer: rename /var/lib/docker/image/(.+) /var/lib/docker/image/(.+): directory not empty.*"
            }
        ]
    }
kind: ConfigMap
metadata:
  name: node-problem-detector-config
  namespace: kube-system
```

#### daemonset yaml

```yaml
[root@10-23-20-155 node-problem-detector]# cat node-problem-detector.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-problem-detector
  namespace: kube-system
  labels:
    app: node-problem-detector
spec:
  selector:
    matchLabels:
      app: node-problem-detector
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      serviceAccountName: node-problem-detector
      containers:
      - name: node-problem-detector
        command:
        - "/bin/sh"
        - "-c"
        - "/node-problem-detector --logtostderr --config.system-log-monitor=/config/kernel-monitor.json,/config/docker-monitor.json"
        #image: gcr.io/node-problem-detector/node-problem-detector:v0.8.7
        image: harbor.ats.io/gcr.io/node-problem-detector/node-problem-detector:v0.8.7
        resources:
          limits:
            cpu: 10m
            memory: 80Mi
          requests:
            cpu: 10m
            memory: 80Mi
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure node problem detector is in the same timezone
        # with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: config
          mountPath: /config
          readOnly: true
        - name: journald
          mountPath: /var/log/journal
      volumes:
      - name: journald
        hostPath:
          path: /var/log/journal
          type: ""
      - name: log
        # Config `log` to your system log directory
        hostPath:
          path: /var/log
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config
        configMap:
          name: node-problem-detector-config
          items:
          - key: kernel-monitor.json
            path: kernel-monitor.json
          - key: docker-monitor.json
            path: docker-monitor.json
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
```

#### result
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/43020699/133869487-d660444e-c2c6-45cf-a6fd-015fbbf8b540.png">

#### outout log
```shell
I0918 10:15:18.932874       8 log_monitor.go:160] New status generated: &{Source:kernel-monitor Events:[{Severity:info Timestamp:2021-09-18 10:15:18.930078 +0800 CST Reason:DockerHung Message:Node condition KernelDeadlock is now: True, reason: DockerHung}] Conditions:[{Type:KernelDeadlock Status:True Transition:2021-09-18 10:15:18.930078 +0800 CST Reason:DockerHung Message:task docker:7 blocked for more than 300 seconds.}]}
I0918 10:16:31.363374       8 log_monitor.go:160] New status generated: &{Source:kernel-monitor Events:[{Severity:warn Timestamp:2021-09-18 10:16:31.362765 +0800 CST Reason:TaskHung Message:task docker:7 blocked for more than 200 seconds.}] Conditions:[{Type:KernelDeadlock Status:True Transition:2021-09-18 10:15:18.930078 +0800 CST Reason:DockerHung Message:task docker:7 blocked for more than 300 seconds.}]}
I0918 10:16:31.363639       8 log_monitor.go:160] New status generated: &{Source:kernel-monitor Events:[] Conditions:[{Type:KernelDeadlock Status:True Transition:2021-09-18 10:15:18.930078 +0800 CST Reason:DockerHung Message:task docker:7 blocked for more than 300 seconds.}]}
```

#### issues
- How to return to normal status after the test statement is executed?
- When I replace the test statement time from 300 seconds to 200 seconds, why NPG log output is always 300?
