### ISSUE TITLE
health-checker-containerd fails on bottlerocketOS

### ISSUE THREAD

**Issue by michalschott** [kubernetes/node-problem-detector#707]
```
# /home/kubernetes/bin/health-checker --component=cri
I1005 12:01:11.493394      43 health_checker.go:172] command /usr/bin/crictl --runtime-endpoint=unix:///var/run/containerd/containerd.sock pods --latest failed: fork/exec /usr/bin/crictl: no such file or directory, []
I1005 12:01:11.496574      43 health_checker.go:172] command /bin/systemctl show containerd --property=InactiveExitTimestamp failed: exit status 1, []
I1005 12:01:11.496740      43 health_checker.go:86] error in getting uptime for cri: exit status 1
cri:containerd was found unhealthy; repair flag : true

# /usr/bin/crictl --runtime-endpoint=unix:///var/run/containerd/containerd.sock pods --latest
sh: 18: /usr/bin/crictl: not found

# /bin/systemctl show containerd --property=InactiveExitTimestamp
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

**Comment by michalschott** [comment]
Based on https://bytemeta.vip/repo/kubernetes/node-problem-detector/issues/683 I've managed to solve it with custom NPD container.

Dockerfile:
```
FROM registry.k8s.io/node-problem-detector/node-problem-detector:v0.8.12 as builder

# Install crictl
ARG TARGETOS
ARG TARGETARCH
#`BUILDX_ARCH` will be used in the buildx package download URL
# The required format is in `TARGETOS-TARGETARCH`
# Set it default to linux-amd64 to make the Dockerfile
# works with / without buildkit
ENV BUILDX_ARCH="${TARGETOS:-linux}-${TARGETARCH:-amd64}"

ARG VERSION="v1.25.0"
RUN apt-get -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -qq -y curl unzip < /dev/null > /dev/null && \
    rm -rf /var/cache/apt/* && \
    curl -sLO https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-${VERSION}-${BUILDX_ARCH}.tar.gz && \
    tar zxvf crictl-$VERSION-${BUILDX_ARCH}.tar.gz -C /usr/bin && \
    rm -f crictl-$VERSION-${BUILDX_ARCH}.tar.gz && \
    apt-get -qq autoremove curl unzip
```

Update daemonset manifest with:
```
spec.template.spec.containers.0.volumeMounts:
  - mountPath: /var/run/containerd/containerd.sock
    name: containerd

spec.template.spec.volumes:
  - name: containerd
    hostPath:
      path: /run/dockershim.sock
      type: Socket
```

Still would be handy to have CRI installed in NPD out of the box.

**Comment by btiernay** [comment]
@michalschott Did you ever make any progress with this?
```
# /bin/systemctl show containerd --property=InactiveExitTimestamp
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

**Comment by michalschott** [comment]
@btiernay never had that problem once I build own container and updated manifest - make sure you have updated mountPaths.

**Comment by btiernay** [comment]
@michalschott I'm curious how you got around the SELinux constraints in Bottlerocket with `systemctl`. I had install a couple of new packages:

```dockerfile
RUN apt-get -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -qq -y --allow-change-held-packages libcap2 systemd strace < /dev/null > /dev/null && \
    rm -rf /var/cache/apt/* && \
    curl -sLO https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-${VERSION}-${BUILDX_ARCH}.tar.gz && \
    tar zxvf crictl-$VERSION-${BUILDX_ARCH}.tar.gz -C /usr/bin && \
    rm -f crictl-$VERSION-${BUILDX_ARCH}.tar.gz && \
    apt-get -qq autoremove curl unzip
```

And then run with `SYSTEMD_IGNORE_CHROOT=1` in the environment.  But even still, I hit MAC issues after configuring SELinux labels in my DaemonSet:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  template:
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - name: node-problem-detector
          securityContext:
            privileged: true
            seLinuxOptions:
              user: system_u
              role: system_r
              type: super_t
              level: s0
```

Curious how you got around that. 

FYI - continuing the discussion with Bottlerocket community here:
https://github.com/bottlerocket-os/bottlerocket/discussions/3156

And for the overall future of the integration here:
https://github.com/bottlerocket-os/bottlerocket/discussions/3156

Please chime if you are so inclined!
