### ISSUE TITLE
Example deployment manifests do not grant node-problem-detector the permissions it needs

### ISSUE THREAD

**Issue by dobesv** [kubernetes/node-problem-detector#791]
In order to deploy node-problem-detector you will need to create a service account and bind a cluster role to it.

e.g. 

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-problem-detector
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: npd-binding
  labels:
    kubernetes.io/cluster-service: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-problem-detector
subjects:
- kind: ServiceAccount
  name: node-problem-detector
  namespace: kube-system

```

And set `serviceAccountName` in the DaemonSet (https://github.com/kubernetes/node-problem-detector/blob/master/deployment/node-problem-detector.yaml)
