### ISSUE TITLE
Networking probes

### ISSUE THREAD

**Issue by aojea** [kubernetes/node-problem-detector#991]
Talked with @danwinship offline, it will be nice to be able to report

- Pod network problems
- DNS cluster problems
- Services problems

It should not be hard to provide some basic plugins that provide some basic checks, if we can figure out the best way to obtain the information needed

**Comment by googs1025** [comment]
We currently have some pods such as cni network plug-ins, and we also want to detect its health status.

**Comment by aojea** [comment]
> pods such as cni network plug-ins

why current Pod Probes are not valid?

**Comment by googs1025** [comment]
Using pod probe can let us know whether the pod is alive, but it does not seem to convert to node condition. Because we have a custom daemonset program, we want when daemonset agents are crashed, they will not be scheduled to this node. If this feature is not provided, we need to implement similar features ourselves.

**Comment by aojea** [comment]
/unassign

I'm not able to work on this soon but is a good opportunity to contribute, @aroradaman @adrianmoisey ... strawman approach


test `kubernetes.default` resolves, this is guaranteed to work and this will test kubernetes dns

test `curl https://kubernetes.default` works, this will test Services work

**Comment by adrianmoisey** [comment]
Hmmm... how have I never seen this project before?
This looks like a fun one, tanks for the tag.
/assign 

(@aroradaman happy to pair with you if you want?)

**Comment by sebhoss** [comment]
We have tests like this to check for IPv4 and IPv6 connectivity:

```shell
    #!/bin/bash

    # Ping an IPv4 address to check connectivity
    if ping -4 -c 1 -w 5 -q 1.0.0.1 1>/dev/null 2>&1; then
      echo "Can ping IPv4 address"
      exit 0
    else
      echo "Cannot ping IPv4 address"
      exit 1
    fi
```

```shell
    #!/bin/bash

    # Ping an IPv6 address to check connectivity
    if ping -6 -c 1 -w 5 -q 2606:4700:4700::1001 1>/dev/null 2>&1; then
      echo "Can ping IPv6 address"
      exit 0
    else
      echo "Cannot ping IPv6 address"
      exit 1
    fi
```

Would it make sense to upstream these? The currently published container image does not contain `ping` and therefore would require an additional package.

**Comment by aojea** [comment]
I'm not familiar with the image building and requirements, @hakman is adding the `ping` program much of a problem?

**Comment by danwinship** [comment]
What are you pinging? Note the pod network is not required to carry pings.

**Comment by sebhoss** [comment]
Those are the alternative IPs for Cloudflares DNS service: https://one.one.one.one/dns/. Are you saying that those pings should work without a working network? In our case, we have seen that nodes without IPv6 connectivity cannot ping the IPv6 address and therefore end up with the expected node condition.

**Comment by danwinship** [comment]
No, I just didn't know what those IPs were supposed to be (your comment didn't mention "DNS" anywhere), and was pointing out that if you were saying "we should test that pod X is pingable", then you can't actually reliably do that.

Testing that cloudflare DNS is pingable is not a generically useful check either, since the cluster may be firewalled in various ways... There is no public IP address that is guaranteed to be reachable from arbitrary clusters.

**Comment by sebhoss** [comment]
ah yeah sorry - I misunderstood what you were saying. 

It's true that this check is not guaranteed to work for all clusters out there, especially because not every cluster run dual stack configuration. However, for those who are interested in a check like the above, here is what we did:

1. Extend the official node-problem-detector-image to install `iputils-ping` (the package which contains `ping`). Our containerfile looks like this:
```dockerfile
FROM registry.k8s.io/node-problem-detector/node-problem-detector:v1.35.1

RUN clean-install iputils-ping
```
2. Create a `ConfigMap` containing the check for IPv4 connectivity (only required if you have IPv4):
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipv4-connection-monitor
data:
  check_ipv4_connection.sh: |
    #!/bin/bash

    # Ping an IPv4 address to check connectivity
    if ping -4 -c 1 -w 5 -q 1.0.0.1 1>/dev/null 2>&1; then
      echo "Can ping IPv4 address"
      exit 0
    else
      echo "Cannot ping IPv4 address"
      exit 1
    fi
```
3. Create a `ConfigMap` containing the check for IPv6 connectivity (only required if you have IPv6):
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipv6-connection-monitor
data:
  check_ipv6_connection.sh: |
    #!/bin/bash

    # Ping an IPv6 address to check connectivity
    if ping -6 -c 1 -w 5 -q 2606:4700:4700::1001 1>/dev/null 2>&1; then
      echo "Can ping IPv6 address"
      exit 0
    else
      echo "Cannot ping IPv6 address"
      exit 1
    fi
```
4. Define custom monitors in a `ConfigMap` (adjust for IPv4/IPv6 availability):
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-problem-detector-custom-config
data:
  ipv4-connection-monitor.json: |
    {
      "plugin": "custom",
      "pluginConfig": {
        "invoke_interval": "30s",
        "timeout": "5s",
        "max_output_length": 80,
        "concurrency": 1,
        "enable_message_change_based_condition_update": true
      },
      "source": "ipv4-connection-monitor",
      "metricsReporting": true,
      "conditions": [
        {
          "type": "IPv4Problem",
          "reason": "IPv4ConnectionUp",
          "message": "IPv4 connection is established"
        }
      ],
      "rules": [
        {
          "type": "temporary",
          "reason": "IPv4ConnectionDown",
          "path": "/plugins/check_ipv4_connection.sh",
          "timeout": "3s"
        },
        {
          "type": "permanent",
          "condition": "IPv4Problem",
          "reason": "IPv4ConnectionDown",
          "path": "/plugins/check_ipv4_connection.sh",
          "timeout": "3s"
        }
      ]
    }
  ipv6-connection-monitor.json: |
    {
      "plugin": "custom",
      "pluginConfig": {
        "invoke_interval": "30s",
        "timeout": "5s",
        "max_output_length": 80,
        "concurrency": 1,
        "enable_message_change_based_condition_update": true
      },
      "source": "ipv6-connection-monitor",
      "metricsReporting": true,
      "conditions": [
        {
          "type": "IPv6Problem",
          "reason": "IPv6ConnectionUp",
          "message": "IPv6 connection is established"
        }
      ],
      "rules": [
        {
          "type": "temporary",
          "reason": "IPv6ConnectionDown",
          "path": "/plugins/check_ipv6_connection.sh",
          "timeout": "3s"
        },
        {
          "type": "permanent",
          "condition": "IPv6Problem",
          "reason": "IPv6ConnectionDown",
          "path": "/plugins/check_ipv6_connection.sh",
          "timeout": "3s"
        }
      ]
    }
```
5. Mount the `ConfigMaps` into the NPD `DaemonSet` (I removed the uninteresting parts here):
```yaml
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-problem-detector
spec:
  template:
    spec:
      containers:
        - name: node-problem-detector
          command:
            - /bin/sh
            - -c
            - 'exec /node-problem-detector ...'
          volumeMounts:
            - name: custom-config
              mountPath: /custom-config
              readOnly: true
            - mountPath: /plugins/check_ipv4_connection.sh
              name: ipv4-connection-monitor
              readOnly: true
              subPath: check_ipv4_connection.sh
            - mountPath: /plugins/check_ipv6_connection.sh
              name: ipv6-connection-monitor
              readOnly: true
              subPath: check_ipv6_connection.sh
      volumes:
        - name: custom-config
          configMap:
            name: node-problem-detector-custom-config
        - configMap:
            name: ipv4-connection-monitor
          name: ipv4-connection-monitor
        - configMap:
            name: ipv6-connection-monitor
          name: ipv6-connection-monitor
```
6. Adjust the `exec` line in the NPD `DaemonSet` to contain `--config.custom-plugin-monitor=/custom-config/ipv4-connection-monitor.json,/custom-config/ipv6-connection-monitor.json` (adjust in case you used different paths)

If your cluster is not supposed to talk to the internet or you do not want to ping cloudflare owned IPs, adjust the checks in step 2 & 3. The end result is something like this:

```
Conditions:                                                                                                                                                                                                                                                                                           
  Type                     Status  LastHeartbeatTime                 LastTransitionTime                Reason                        Message                                                                                                                                                          
  ----                     ------  -----------------                 ------------------                ------                        -------                                                                                                                                                          
  IPv4Problem              False   Mon, 29 Dec 2025 15:11:45 +0100   Wed, 24 Dec 2025 07:36:51 +0100   IPv4ConnectionUp              IPv4 connection is established
  IPv6Problem              False   Mon, 29 Dec 2025 15:11:45 +0100   Wed, 24 Dec 2025 07:36:51 +0100   IPv6ConnectionUp              IPv6 connection is established
```
